name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: docker create --name drifuzz --privileged -it ubuntu:20.04
      - run: docker start -ai drifuzz < ${{ github.workspace }}/docker_script.sh
      - run: docker container commit drifuzz drifuzz-docker:latest
      - run: docker image tag drifuzz-docker:latest buszk/drifuzz-docker:latest
      - run: docker push buszk/drifuzz-docker:latest